import Head from 'next/head'
import { Inter } from '@next/font/google'
import Slider from '../components/Slider'
import Packages from '../components/Packages'
import Consultancy from '../components/Consultancy'
import Benifits from '../components/Benifits'
import Instruments from '../components/Instruments'
import Products from '../components/Products'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  
  return (
    <>
      <Head>
        <title>Gymzilla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slider></Slider>
        <Packages></Packages>
        <Consultancy></Consultancy>
        <Benifits></Benifits>
        <Instruments></Instruments>
        <Products></Products>
      </main>
    </>
  )
}
